# -*- coding: utf-8 -*-
"""@yagpt_vniims_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9riIuexXdla_DmXgOg8Byq84OLwn1Ig
"""

import os
import io
import pickle
import numpy as np
import json
import scipy
from scipy.spatial.distance import cdist
import re
import requests
import time


ID_FOLDER = 'b1gmbmom8qe6nho8em9o'
OAuth_token = 'y0_AgAAAABw6jr2AATuwQAAAAEGWX2tAADeOEZ3lbpDC5ChJOOggtropfOo4Q'

# URL для получения токена
URL = "https://iam.api.cloud.yandex.net/iam/v1/tokens"
# Получение IAM-токена (с помощью request)
headers = {"Content-Type": "application/json"}
data = {
    "yandexPassportOauthToken": OAuth_token
}
response = requests.post(URL, headers=headers, json=data)
IAM_TOKEN = response.json()["iamToken"]
expiresAt = response.json()["expiresAt"]

#Выгрузим подготовленную базу для embedding из файла
response = requests.get('https://storage.yandexcloud.net/vniims/doc_texts_03_03.pkl')
file = io.BytesIO(response.content)
doc_texts = pickle.load(file)

#загрузка массива embeddings из стороннего источника
response = requests.get('https://storage.yandexcloud.net/vniims/docs_embedding_03_03.npy')
file = io.BytesIO(response.content)
docs_embedding = np.load(file)

#Выгрузим подготовленную базу metadata для embedding из файла стороннего источника
response = requests.get('https://storage.yandexcloud.net/vniims/doc_metadata_03_04.pkl')
file = io.BytesIO(response.content)
doc_metadata =  pickle.load(file)

#Embedding YandexGPT
doc_uri = f"emb://{ID_FOLDER}/text-search-doc/latest"
query_uri = f"emb://{ID_FOLDER}/text-search-query/latest"

embed_url = "https://llm.api.cloud.yandex.net:443/foundationModels/v1/textEmbedding"
headers = {"Content-Type": "application/json", "Authorization": f"Bearer {IAM_TOKEN}", "x-folder-id": f"{ID_FOLDER}"}

def get_embedding(text: str, text_type: str = "doc") -> np.array:
    # URL для получения токена
    URL = "https://iam.api.cloud.yandex.net/iam/v1/tokens"

    # Получение IAM-токена (с помощью request)
    import requests

    headers = {"Content-Type": "application/json"}

    data = {
        "yandexPassportOauthToken": OAuth_token
    }

    response = requests.post(URL, headers=headers, json=data)

    IAM_TOKEN = response.json()["iamToken"]
    expiresAt = response.json()["expiresAt"]

    #print(f'Ваш токен действителен до: {expiresAt}')

    doc_uri = f"emb://{ID_FOLDER}/text-search-doc/latest"
    query_uri = f"emb://{ID_FOLDER}/text-search-query/latest"

    embed_url = "https://llm.api.cloud.yandex.net:443/foundationModels/v1/textEmbedding"
    headers = {"Content-Type": "application/json", "Authorization": f"Bearer {IAM_TOKEN}", "x-folder-id": f"{ID_FOLDER}"}
    query_data = {
        "modelUri": doc_uri if text_type == "doc" else query_uri,
        "text": text,
    }

    return np.array(
        requests.post(embed_url, json=query_data, headers=headers).json()["embedding"]
    )

    #функция вывода k релевантных чанков по косинусному расстоянию
def get_k_max_indices(arr, k):
    indices = np.argpartition(arr, -k)[-k:]
    return indices

#Функция получения релевантных чанков и метаданных и подготовка вопроса в LLM:
def chunks_metadata_question(query_text):
    #получем embedding вопроса
    query_embedding = get_embedding(query_text, text_type="query")
    # Вычисляем косинусное расстояние
    dist = cdist(query_embedding[None, :], docs_embedding, metric="cosine")
    # Вычисляем косинусное сходство
    sim = 1 - dist
    k = 3 #количество релевантных чанков
    indices = get_k_max_indices(sim, k)
    #находим индексы k релевантных чанков
    ind_k = indices[0][-k:]
    #выведем косинусное расстояние для найденных чанков
    #for ind in ind_k: print(sim[0, ind])
    #Подтягиваем релевантные чанки из базы данных
    docs = []
    doc_meta = []
    for ind in ind_k:
        docs.append(doc_texts[ind])
        doc_meta.append(doc_metadata[ind])
        #print(ind)
    message_content = re.sub(r'\n{2}', ' ', '\n '.join([f'\nОтрывок документа ' + doc_meta[i] + '. ' + doc + '\n' for i, doc in enumerate(docs)]))
    print (message_content)
    question = f"Запрос: \n{query_text}\n. Документы с информацией для ответа пользователю: {message_content}"
    return question

response = requests.get('https://drive.google.com/uc?export=download&id=188aSbPxnyB5BRyIjmUb1GcMDbJIIYpxo')
response.raise_for_status()
system_out = response.text

response = requests.get('https://drive.google.com/uc?export=download&id=1b5XOE0uTir5KRiKAU_uOOcuZdjSZGf2x')
response.raise_for_status()
system_in = response.text

#Функция обращения к модели YandexGPT Pro
def get_gpt_ya_response (ID_FOLDER, question, system):
    # URL для получения токена
    URL = "https://iam.api.cloud.yandex.net/iam/v1/tokens"
    # Получение IAM-токена (с помощью request)
    headers = {"Content-Type": "application/json"}
    data = {
        "yandexPassportOauthToken": OAuth_token
    }
    response = requests.post(URL, headers=headers, json=data)
    IAM_TOKEN = response.json()["iamToken"]
    expiresAt = response.json()["expiresAt"]
    prompt = {
        "modelUri": f"gpt://{ID_FOLDER}/yandexgpt", # yandexgpt - модель YandexGPT pro
        "completionOptions": {
            "stream": False,
            "temperature": 0.0,
            "maxTokens": 2000
        },
            "messages": [
                {
                "role": "system",
                "text": f"{system}"
                },
                {
                "role": "user",
                "text": f"{question}"
                }
            ]
    }
    url = "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {IAM_TOKEN}"
    }
    response = requests.post(url, headers=headers, json=prompt)
    json_data = json.loads(response.text)
    answer = json_data['result']['alternatives'][0]['message']['text']
    return answer

#функция объединение запросов моделей
def answer_ya_gpt(question):
  question_paraphrase = get_gpt_ya_response (ID_FOLDER, question, system_in)
  print (question_paraphrase)
  time.sleep(10)
  pattern = r'Запрос:\s*(.*)'
  match = re.search(pattern, question_paraphrase)
  if match:
      result = match.group(1)  # извлекаем текст из группы
      print (result)
      question_sum = f'Ответьте на вопрос пользователя: {question}. {chunks_metadata_question(result)}'
      answer_gpt = get_gpt_ya_response (ID_FOLDER, question_sum, system_out)
  else:
      answer_gpt = question_paraphrase
  print(answer_gpt)
  return answer_gpt


def send_message(chat_id, text):
    url = 'https://api.telegram.org/bot7303915442:AAG52WIkzsLPlTkz_x0xiL4BdX6SHuuoVF8/sendMessage'
    max_length = 4096

    # Разбиваем текст на части, если он превышает max_length
    for i in range(0, len(text), max_length):
        part = text[i:i+max_length]
        requests.post(
            url,
            json={
                'chat_id': chat_id,
                'text': part
            }
        )

def handler(event, context):
    data_load = json.loads(event.get('body'))
    #print (data_load)

    chat_id = data_load['message']['chat']['id']
    answer_text = data_load['message']['text']

    if answer_text == '/start':
        send_message(
            chat_id,
            'Здравствуйте! Я прототип нейросетевого эксперта Всероссийского научно-исследовательского института метрологической службы. Готов ответить на Ваши вопросы в области обеспечения единства измерений, технического регулирования и стандартизации.'
        )
    else:
        response_text = answer_ya_gpt(answer_text)
        send_message(chat_id, response_text)

    return {
        'statusCode': 200,
        'body': 'Hello World!',
    }